name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the sources
        uses: actions/checkout@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: |
          docker build . --tag ghcr.io/pastorrob/temp-cicd
          docker run ghcr.io/pastor-robert/temp-cicd:latest
          docker push ghcr.io/pastor-robert//temp-cicd:latest
